# Generated by Django 4.1.7 on 2023-03-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='gameDrawn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamedata',
            name='gameLost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamedata',
            name='gameWon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gameDrawn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gameLost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gameWon',
            field=models.IntegerField(default=0),
        ),
    ]
