# Generated by Django 4.1.7 on 2023-03-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_gamedata_gamedrawn_gamedata_gamelost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='numberOfGames',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='numberOfGames',
            field=models.IntegerField(default=0),
        ),
    ]
